version: '3.3'

services:
  api:
    container_name: watt_api_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
