export default {
  MAIN_BNB: "MAIN_BNB",
  TOKEN_BNB: "TOKEN_BNB",
  CUSTOM_TOKEN_BNB: "CUSTOM_TOKEN_BNB",

  MAIN_ETH: "MAIN_ETH",
  TOKEN_ETH: "TOKEN_ETH",
  CUSTOM_TOKEN_ETH: "CUSTOM_TOKEN_ETH",

  MAIN_BTC: "MAIN_BTC",
  TOKEN_BTC: "TOKEN_BTC",
  CUSTOM_TOKEN_BTC: "CUSTOM_TOKEN_BTC",

  MAIN_LTC: "MAIN_LTC",
  TOKEN_LTC: "TOKEN_LTC",
  CUSTOM_TOKEN_LTC: "CUSTOM_TOKEN_LTC",

  MAIN_POLYGON: "MAIN_POLYGON",
  TOKEN_POLYGON: "TOKEN_POLYGON",
  CUSTOM_TOKEN_POLYGON: "CUSTOM_TOKEN_POLYGON",

  MAIN_SOL: "MAIN_SOL",
  TOKEN_SOL: "TOKEN_SOL",
  CUSTOM_TOKEN_SOL: "CUSTOM_TOKEN_SOL"
};
